[workspace]
members = ["cargo:."]

[dist]
# The preferred dist version to use in CI
cargo-dist-version = "0.30.2"
# CI backends to support
ci = "github"
# Target platforms to build apps for
targets = [
  "x86_64-unknown-linux-gnu",
  "aarch64-unknown-linux-gnu",
  "aarch64-apple-darwin",
  "x86_64-pc-windows-msvc",
]
# The installers to generate for each app
installers = ["shell", "powershell"]
# Where to host releases
hosting = "github"
# PR run mode
pr-run-mode = "plan"

# Use custom runners for ARM Linux builds
[dist.github-custom-runners]
aarch64-unknown-linux-gnu = "depot-ubuntu-22.04-arm-8"
